version = 1

exclude_patterns = [
  'tests/data/*',
]

test_patterns = [
  'tests/*'
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  max_line_length = 90
  skip_doc_coverage = ["module", "magic", "init"]
